name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set-Up
        run: sudo apt update && sudo apt install -y git clang curl libssl-dev llvm libudev-dev cmake protobuf-compiler

      - name: Cache Build artefacts
        uses: Swatinem/rust-cache@v2.7.0
        with:
          shared-key: test

      - name: Install cargo-nextest
        run: if ! which cargo-nextest &> /dev/null; then cargo install cargo-nextest; fi

      # Pallet
      - name: Configure CI
        run: mkdir .config && echo -e "[profile.ci.junit]\npath = \"junit.xml\"" > .config/nextest.toml
      - name: Run tests
        run: cargo nextest run --release --profile ci
      - name: Report pallet test results
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: integration-tests
          path: target/nextest/ci/junit.xml
          reporter: jest-junit